const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';

const MUTIPLE = 'MUTIPLE';
const DIVIDE  = 'DIVIDE';

const GET_CHANNEL_INFO = 'GET_CHANNEL_INFO';

export {
    INCREMENT,
    DECREMENT,
    MUTIPLE,
    DIVIDE,
    GET_CHANNEL_INFO,
}